# é…ç½®æ–‡ä»¶è¯·ä¸¥æ ¼éµå¾ªyamlè¯­æ³•æ ¼å¼ï¼Œyamlå­¦ä¹ åœ°å€:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# å®šæ—¶æ—¶é—´
alarm_timed: '9:30'

# æ ¼è¨€æ¸ é“
# 1 : ONEâ—ä¸€ä¸ª
# 2 : è¯éœ¸ï¼ˆæ¯æ—¥è‹±è¯­ï¼ŒåŒè¯­ï¼‰
# 3 : åœŸå‘³æƒ…è¯
dictum_channel: 2

friend_infos:
  -
    type: 'person'
    # æœ‹å‹å¾®ä¿¡æ˜µç§°
    wechat_name: 'éƒ‘ç©æ˜Ÿ'
    # æœ‹å‹æ‰€åœ¨åŸå¸‚
    city_name: 'å¹¿å·'
    # è¿è¡Œå¼€å§‹æ—¶é—´
    start_date: '2019-06-11'
    # ç•™è¨€ï¼ˆå¯ç©ºï¼‰
    sweet_words: ''

  -
    type: 'group'
    # ç¾¤ç»„å¾®ä¿¡æ˜µç§°
    wechat_name: 'ä¸€ä¸ªæµ‹è¯•ç¾¤'
    # ç¾¤ç»„åŸå¸‚
    city_name: 'æ±•å¤´'
    # è¿è¡Œå¼€å§‹æ—¶é—´
    start_date: ''
    # ç•™è¨€
    sweet_words: ''

  - type: 'group'
    wechat_name: 'ğŸˆšï¸è¡¨æƒ…åŒ…ğŸ˜ğŸ«'
    city_name: 'ç æµ·'
    start_date: '2019-06-11'
    sweet_words: ''

#  -
#    wechat_name: 'ğŸ‘ğŸ”ğŸ¶ğŸ â¤ï¸ğŸ”†'
#    city_name: 'æ±•å¤´'
#    start_data: ''
#    sweet_words: ''
